/* =====================================================================
   cviky.js – katalog cviků (vlastní váha + židle + stupínek 20 cm + podložka)
   Každý cvik: id (= klíč animace v FitAnim), name, cat, sh (zátěž ramene 0 = žádná, 1 = mírná – opora na předloktí/ruce),
   sides (cvičí se na každou stranu), type 'reps' | 'time', spr (s na opakování – jen pro odhad délky),
   lad [odL, doL, min, max] = dávka roste lineárně s úrovní L mezi odL a doL (pak už jen max),
   unlock (od jaké úrovně se cvik zařazuje), fam (rodina – v plánu je vždy jen nejtěžší odemčená varianta),
   cues (na co si dát pozor), why (proč – hlavně pro fotbal), alt (náhrada, když nesedí).
   ===================================================================== */
window.CVIKY = (function () {
  var L = [
    /* ---------------- rozcvička ---------------- */
    { id: 'pochod-koleno', name: 'Pochod / skipink s vysokým kolenem', cat: 'warm', sh: 0, type: 'time', lad: [0, 30, 30, 45],
      cues: ['Koleno do výšky boků', 'Vzpřímený trup, zpevněné břicho', 'Ruce jen volně u těla'],
      why: 'Prokrví nohy a rozehřeje bedrokyčlostehenní sval – motor rychlého náběhu i nápřahu.' },
    { id: 'zakopavani', name: 'Zakopávání na místě', cat: 'warm', sh: 0, type: 'time', lad: [0, 30, 30, 40],
      cues: ['Pata k hýždím', 'Lehce na špičkách', 'Ruce volně'],
      why: 'Rozehřeje zadní stehna – prevence natažení při sprintu.' },
    { id: 'kmihy-vpred', name: 'Kmihy nohou vpřed–vzad (opora o židli)', cat: 'warm', sh: 0, sides: true, type: 'reps', spr: 1.4, lad: [0, 30, 10, 14],
      cues: ['Drž se opěradla jen lehce', 'Švih z kyčle, ne z bederní páteře', 'Postupně zvětšuj rozsah'],
      why: 'Dynamicky otevírá kyčel v rovině nápřahu a dokopu střely.' },
    { id: 'kmihy-stranou', name: 'Kmihy nohou do stran (opora o židli)', cat: 'warm', sh: 0, sides: true, type: 'reps', spr: 1.4, lad: [0, 30, 10, 14],
      cues: ['Stůj zpříma, ruce v bok (nebo se přidrž opěradla židle)', 'Noha kmitá před tělem zleva doprava', 'Boky zůstávají čelem vpřed'],
      why: 'Rozhýbe třísla a odtahovače – zpracování balónu vnitřní stranou, změny směru.' },
    { id: 'kyc-kruhy', name: 'Otevírání brány (kroužení kolenem)', cat: 'warm', sh: 0, sides: true, type: 'reps', spr: 2.5, lad: [0, 30, 6, 8],
      cues: ['Koleno nahoru, pak ho vytoč do strany a dolů', 'Stůj zpříma, klidně se přidrž židle', 'Pomalu, v plném rozsahu'],
      why: 'Rotace v kyčli = větší rozsah při přihrávkách a obratech.' },

    /* ---------------- nohy / síla ---------------- */
    { id: 'drep-zidle', name: 'Dřep na židli', cat: 'legs', fam: 'drep', sh: 0, type: 'reps', spr: 3, lad: [0, 5, 10, 15], unlock: 0,
      cues: ['Nohy na šířku boků, špičky lehce ven', 'Zadek dozadu, jen se dotkni sedáku a hned nahoru', 'Kolena míří nad špičky'],
      why: 'Základ síly stehen a hýždí – odraz, souboje, sprint.' },
    { id: 'drep', name: 'Dřep', cat: 'legs', fam: 'drep', sh: 0, type: 'reps', spr: 3, lad: [5, 14, 12, 20], unlock: 5,
      cues: ['Hrudník nahoru, záda rovná', 'Do hloubky, kam to jde s rovnými zády', 'Paty celé na zemi'],
      why: 'Silné stehno = silnější a stabilnější stojná noha při střele.' },
    { id: 'drep-pauza', name: 'Dřep s výdrží dole (3 s)', cat: 'legs', fam: 'drep', sh: 0, type: 'reps', spr: 5.5, lad: [14, 40, 10, 16], unlock: 14,
      cues: ['Dole 3 vteřiny drž, napni břicho', 'Nahoru dynamicky', 'Kolena nepadají dovnitř'],
      why: 'Síla v hlubokém postavení – souboje a výskoky.' },
    { id: 'vypad-vzad', name: 'Výpad vzad', cat: 'legs', fam: 'vypad', sh: 0, sides: true, type: 'reps', spr: 3.2, lad: [0, 9, 6, 12], unlock: 0,
      cues: ['Krok dozadu, zadní koleno skoro k zemi', 'Přední koleno nad kotníkem', 'Odraz přední patou zpět'],
      why: 'Jednonohá síla a stabilita kolene – každá změna směru je jednonohá.' },
    { id: 'bulhar', name: 'Bulharský dřep (zadní noha na židli)', cat: 'legs', fam: 'vypad', sh: 0, sides: true, type: 'reps', spr: 3.6, lad: [9, 40, 6, 14], unlock: 9,
      cues: ['Nárt zadní nohy na sedáku', 'Klesej rovně dolů', 'Přední koleno nad špičkou, ne dovnitř'],
      why: 'Nejlepší domácí cvik na sílu stojné nohy a pružnost flexoru zadní nohy.' },
    { id: 'vystup', name: 'Výstup na stupínek', cat: 'legs', fam: 'vystup', sh: 0, sides: true, type: 'reps', spr: 2.6, lad: [0, 8, 8, 14], unlock: 0,
      cues: ['Celé chodidlo na stupínku', 'Vytlač se nohou nahoře, ne odrazem spodní', 'Dolů pomalu'],
      why: 'Síla a kontrola jedné nohy, šetrné ke kolenům.' },
    { id: 'vystup-koleno', name: 'Výstup na stupínek s vytažením kolene', cat: 'legs', fam: 'vystup', sh: 0, sides: true, type: 'reps', spr: 2.8, lad: [8, 40, 8, 15], unlock: 8,
      cues: ['Nahoře vytáhni druhé koleno do výšky boků', 'Chvilku drž rovnováhu', 'Zpevněný trup'],
      why: 'Rovnováha na stojné noze + síla švihové nohy = lepší střela.' },
    { id: 'lytka', name: 'Výpony na stupínku', cat: 'legs', fam: 'lytka', sh: 0, type: 'reps', spr: 2.4, lad: [0, 10, 15, 25], unlock: 0,
      cues: ['Paty přes hranu stupínku', 'Nahoru co nejvýš, dolů pod úroveň hrany', 'Přidrž se opěradla židle nebo zdi'],
      why: 'Lýtka a Achillovka – sprint, výskok, prevence zranění.' },
    { id: 'lytka-1noha', name: 'Výpony na jedné noze na stupínku', cat: 'legs', fam: 'lytka', sh: 0, sides: true, type: 'reps', spr: 2.4, lad: [10, 40, 10, 20], unlock: 10,
      cues: ['Druhá noha pokrčená za tělem', 'Pomalu dolů 2 s', 'Přidrž se opěradla židle nebo zdi'],
      why: 'Odolnost lýtka a kotníku pro sprinty.' },
    { id: 'rdl-1noha', name: 'Jednonohý mrtvý tah (vlastní váha)', cat: 'legs', sh: 0, sides: true, type: 'reps', spr: 3.6, lad: [2, 40, 6, 12], unlock: 2,
      cues: ['Stojná noha lehce pokrčená', 'Trup a zadní noha jedna linie', 'Boky zůstávají rovně, nevytáčej je'],
      why: 'Zadní stehna + rovnováha – prevence natažení a stabilita při střele.' },
    { id: 'kozacky', name: 'Kozácký dřep', cat: 'legs', sh: 0, sides: true, type: 'reps', spr: 3.6, lad: [4, 40, 5, 10], unlock: 4,
      cues: ['Široký postoj, přenes váhu na jednu nohu', 'Druhá noha natažená, špička nahoru', 'Pata pokrčené nohy na zemi'],
      why: 'Síla + rozsah v tříslech – obrovsky pomáhá hybnosti kyčlí.' },
    { id: 'kopenhagen', name: 'Kodaňský plank (koleno na židli)', cat: 'legs', sh: 1, sides: true, type: 'time', lad: [5, 40, 15, 40], unlock: 5, alt: 'unozovani',
      cues: ['Leh na boku, předloktí pod ramenem', 'Horní koleno na sedáku židle', 'Zvedni boky, tělo v jedné linii'],
      why: 'Prevence zranění třísel č. 1 ve fotbale (adduktory).' },
    { id: 'unozovani', name: 'Unožování vleže na boku', cat: 'legs', sh: 0, sides: true, type: 'reps', spr: 2.4, lad: [0, 40, 10, 20], unlock: 0,
      cues: ['Spodní noha pokrčená, horní natažená', 'Zvedni nohu, špička míří dopředu, ne nahoru', 'Hlava na spodní paži nebo dlani'],
      why: 'Střední hýžďový sval stabilizuje pánev při střele a běhu.' },

    /* ---------------- výbušnost ---------------- */
    { id: 'vyskok-drep', name: 'Dřep s výskokem', cat: 'power', sh: 0, type: 'reps', spr: 2.8, lad: [4, 40, 6, 15], unlock: 4,
      cues: ['Rychle dolů do čtvrtdřepu a výbušně nahoru', 'Doskok měkce přes špičky', 'Kolena míří nad špičky'],
      why: 'Výbušná síla nohou – start, výskok na hlavičku, razance střely.' },
    { id: 'bruslar', name: 'Bruslařské skoky', cat: 'power', sh: 0, type: 'reps', spr: 1.8, lad: [3, 40, 8, 20], unlock: 3,
      cues: ['Skok ze strany na stranu', 'Dopad na jednu nohu, chvilku stabilizuj', 'Počítej každý doskok'],
      why: 'Boční výbušnost a stabilita kolene při změnách směru.' },

    /* ---------------- zpevnění (core) ---------------- */
    { id: 'most', name: 'Most (zvedání pánve)', cat: 'core', fam: 'most', sh: 0, type: 'reps', spr: 3, lad: [0, 4, 12, 20], unlock: 0,
      cues: ['Paty blízko zadku', 'Zatlač patami, stiskni hýždě nahoře', 'Nepřeprohýbej bedra'],
      why: 'Silné hýždě = silný odraz i střela, ulehčení zádům.' },
    { id: 'most-pochod', name: 'Most s pochodem', cat: 'core', fam: 'most', sh: 0, sides: true, type: 'reps', spr: 2.6, lad: [4, 9, 6, 12], unlock: 4,
      cues: ['Drž pánev nahoře a rovně', 'Střídavě zvedni koleno', 'Pánev nesmí klesnout do strany'],
      why: 'Zpevnění pánve při pohybu nohy – přesně to, co děláš při kopu.' },
    { id: 'most-1noha', name: 'Most na jedné noze', cat: 'core', fam: 'most', sh: 0, sides: true, type: 'reps', spr: 3, lad: [9, 15, 8, 14], unlock: 9,
      cues: ['Druhá noha natažená nebo koleno k hrudi', 'Tlač patou', 'Boky rovně'],
      why: 'Jednonohá síla hýždí pro střelu a sprint.' },
    { id: 'most-zidle-1noha', name: 'Most na jedné noze s patou na židli', cat: 'core', fam: 'most', sh: 0, sides: true, type: 'reps', spr: 3.2, lad: [15, 40, 8, 15], unlock: 15,
      cues: ['Pata na sedáku židle', 'Zvedni pánev, stiskni hýždě', 'Pomalu dolů'],
      why: 'Zadní stehna a hýždě v prodloužení – prevence natažení.' },
    { id: 'dead-bug', name: 'Mrtvý brouk (dead bug)', cat: 'core', sh: 0, sides: true, type: 'reps', spr: 3, lad: [0, 40, 6, 14], unlock: 0,
      cues: ['Bedra přitisknutá k zemi', 'Natahuj protilehlou nohu (ruce jen nízko, šetři rameno)', 'Vydechni při natažení'],
      why: 'Zpevnění středu těla – lepší kontrola balónu a souboje.' },
    { id: 'bird-dog', name: 'Ptakopes (bird dog)', cat: 'core', sh: 1, sides: true, type: 'reps', spr: 3.2, lad: [0, 40, 6, 12], unlock: 0, alt: 'dead-bug',
      cues: ['Na kolenou a dlaních, záda rovná', 'Natáhni protilehlou ruku a nohu', 'Pánev se netočí'],
      why: 'Stabilita trupu při pohybu končetin – rovnováha při kopu.' },
    { id: 'plank', name: 'Plank na předloktích', cat: 'core', sh: 1, type: 'time', lad: [0, 40, 20, 75], unlock: 0, alt: 'hollow',
      cues: ['Lokty pod rameny', 'Tělo v jedné linii, zadek nezvedej', 'Stiskni hýždě a břicho'],
      why: 'Celkové zpevnění – stabilní tělo při souboji o míč.' },
    { id: 'bocni-plank', name: 'Boční plank na předloktí', cat: 'core', sh: 1, sides: true, type: 'time', lad: [2, 40, 15, 45], unlock: 2, alt: 'unozovani',
      cues: ['Loket pod ramenem', 'Boky nahoru, tělo v linii', 'Klidně kolena pokrčená (lehčí)'],
      why: 'Boční zpevnění – odolnost v soubojích ramenem na rameno.' },
    { id: 'hollow', name: 'Hollow hold (lodička na zádech)', cat: 'core', sh: 0, type: 'time', lad: [6, 40, 15, 40], unlock: 6,
      cues: ['Bedra přitisknutá k zemi', 'Ramena a nohy lehce nad zemí', 'Ruce podél těla (šetří rameno)'],
      why: 'Pevný střed – přenos síly z nohou do střely.' },
    { id: 'rus-twist', name: 'Ruská rotace', cat: 'core', sh: 0, type: 'reps', spr: 1.6, lad: [2, 40, 10, 24], unlock: 2,
      cues: ['Sed, záda rovná, mírný záklon', 'Rotuj trupem, ne jen rukama', 'Pokročilí: nohy nad zemí'],
      why: 'Rotační síla trupu = razance střely.' },
    { id: 'superman', name: 'Superman (ruce podél těla)', cat: 'core', sh: 0, type: 'reps', spr: 3, lad: [0, 40, 8, 15], unlock: 0,
      cues: ['Leh na břiše, ruce podél těla', 'Zvedni hrudník a nohy kousek nad zem', 'Krk v prodloužení páteře'],
      why: 'Silná záda a hýždě – vzpřímené držení a ochrana zad.' },

    /* ---------------- protažení / mobilita ---------------- */
    { id: 'devadesat', name: '90/90 přetáčení kyčlí', cat: 'mob', sh: 0, type: 'reps', spr: 4, lad: [0, 30, 6, 10],
      cues: ['Sed, obě kolena pokrčená do 90°', 'Přetoč kolena na druhou stranu', 'Záda rovně, ruce za tělem jen lehce'],
      why: 'Vnitřní i vnější rotace kyčle – rozsah pro přihrávky a obraty.' },
    { id: 'wgs', name: 'Nejlepší protažení světa (výpad s rotací)', cat: 'mob', sh: 1, sides: true, type: 'reps', spr: 5, lad: [0, 30, 3, 5], alt: 'flexor',
      cues: ['Hluboký výpad, ruka na zemi', 'Loket ke kotníku, pak rotace hrudníku', 'Paži nahoru jen kam to rameno pustí'],
      why: 'Kyčle + hrudní páteř najednou – ideální pro fotbalisty.' },
    { id: 'flexor', name: 'Protažení flexoru kyčle v kleku', cat: 'mob', sh: 0, sides: true, type: 'time', lad: [0, 30, 30, 45],
      cues: ['Zadní koleno na podložce', 'Podsaď pánev a posuň boky dopředu', 'Neprohýbej se v bedrech'],
      why: 'Uvolní přední stranu kyčle – delší nápřah při střele.' },
    { id: 'hamstring', name: 'Protažení zadního stehna vleže', cat: 'mob', sh: 0, sides: true, type: 'time', lad: [0, 30, 30, 45],
      cues: ['Leh na zádech, natažená noha nahoru', 'Drž ji za stehno (ne za koleno)', 'Druhá noha leží na zemi'],
      why: 'Pružnější zadní stehna – vyšší a uvolněnější švih nohy.' },
    { id: 'figure4', name: 'Protažení hýždí „čtyřka“ vleže', cat: 'mob', sh: 0, sides: true, type: 'time', lad: [0, 30, 30, 45],
      cues: ['Kotník přes koleno druhé nohy', 'Přitáhni spodní nohu k hrudi', 'Ramena a hlava v klidu na zemi'],
      why: 'Uvolní hluboké rotátory kyčle a hýždě.' },
    { id: 'motylek', name: 'Motýlek (protažení třísel)', cat: 'mob', sh: 0, type: 'time', lad: [0, 30, 40, 60],
      cues: ['Sed, chodidla k sobě', 'Kolena pomalu k zemi', 'Rovná záda, předklon z kyčlí'],
      why: 'Rozsah v tříslech – lepší zpracování balónu vnitřní stranou.' },
    { id: 'zabka', name: 'Žabka – houpání vzad', cat: 'mob', sh: 1, type: 'reps', spr: 3, lad: [0, 30, 8, 12], alt: 'motylek',
      cues: ['Na předloktích a kolenou, kolena široko', 'Houpej boky pomalu dozadu k patám', 'Záda rovná'],
      why: 'Aktivní protažení třísel (adduktorů).' },
    { id: 'kocka', name: 'Kočičí hřbet', cat: 'mob', sh: 1, type: 'reps', spr: 4, lad: [0, 30, 6, 10], alt: 'figure4',
      cues: ['Na čtyřech, dlaně pod rameny', 'S výdechem kulatá záda, s nádechem prohnutí', 'Pomalu, obratel po obratli'],
      why: 'Pohyblivost páteře a pánve – základ pro rotaci při střele.' }
  ];

  /* typy tréninkových dnů – střídají se dokola */
  var DNY = [
    { id: 'A', name: 'Nohy & síla střely', emoji: '⚽',
      warm: ['pochod-koleno', 'kmihy-vpred', 'kyc-kruhy'],
      main: ['drep', 'vypad', 'most', 'rdl-1noha', 'vystup', 'lytka', 'kozacky', 'plank'],
      mob: ['flexor', 'hamstring', 'devadesat', 'motylek'] },
    { id: 'B', name: 'Zpevnění & kontrola míče', emoji: '🧱',
      warm: ['zakopavani', 'kmihy-stranou', 'kocka'],
      main: ['dead-bug', 'most', 'bird-dog', 'unozovani', 'kopenhagen', 'hollow', 'plank', 'bocni-plank', 'superman', 'rdl-1noha'],
      mob: ['figure4', 'zabka', 'wgs', 'hamstring'] },
    { id: 'C', name: 'Výbušnost & kyčle', emoji: '⚡',
      warm: ['pochod-koleno', 'kmihy-stranou', 'kyc-kruhy'],
      main: ['vyskok-drep', 'vystup', 'bruslar', 'vypad', 'rus-twist', 'kozacky', 'most', 'dead-bug'],
      mob: ['devadesat', 'flexor', 'wgs', 'motylek'] }
  ];

  var BY = {};
  L.forEach(function (e) { BY[e.id] = e; });
  return { list: L, by: BY, dny: DNY };
})();
